export const Countrylist = [
  { id: 1, alphacode: 'AF', Country: 'Afghanistan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg' },
  { id: 2, alphacode: 'AX', Country: 'Åland Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AX.svg' },
  { id: 3, alphacode: 'AL', Country: 'Albania', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg' },
  { id: 4, alphacode: 'DZ', Country: 'Algeria', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg' },
  { id: 5, alphacode: 'AS', Country: 'American Samoa', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg' },
  { id: 6, alphacode: 'AD', Country: 'Andorra', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg' },
  { id: 7, alphacode: 'AO', Country: 'Angola', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg' },
  { id: 8, alphacode: 'AI', Country: 'Anguilla', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg' },
  { id: 9, alphacode: 'AQ', Country: 'Antarctica', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg' },
  { id: 10, alphacode: 'AG', Country: 'Antigua and Barbuda', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg' },
  { id: 11, alphacode: 'AR', Country: 'Argentina', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg' },
  { id: 12, alphacode: 'AM', Country: 'Armenia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg' },
  { id: 13, alphacode: 'AW', Country: 'Aruba', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg' },
  { id: 14, alphacode: 'AU', Country: 'Australia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg' },
  { id: 15, alphacode: 'AT', Country: 'Austria', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg' },
  { id: 16, alphacode: 'AZ', Country: 'Azerbaijan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg' },
  { id: 17, alphacode: 'BS', Country: 'Bahamas', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg' },
  { id: 18, alphacode: 'BH', Country: 'Bahrain', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg' },
  { id: 19, alphacode: 'BD', Country: 'Bangladesh', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg' },
  { id: 20, alphacode: 'BB', Country: 'Barbados', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg' },
  { id: 21, alphacode: 'BY', Country: 'Belarus', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg' },
  { id: 22, alphacode: 'BE', Country: 'Belgium', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg' },
  { id: 23, alphacode: 'BZ', Country: 'Belize', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg' },
  { id: 24, alphacode: 'BJ', Country: 'Benin', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg' },
  { id: 25, alphacode: 'BM', Country: 'Bermuda', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg' },
  { id: 26, alphacode: 'BT', Country: 'Bhutan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg' },
  { id: 27, alphacode: 'BO', Country: 'Bolivia (Plurinational State of)', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg' },
  { id: 28, alphacode: 'BQ', Country: 'Bonaire, Sint Eustatius and Saba', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BQ.svg' },
  { id: 29, alphacode: 'BA', Country: 'Bosnia and Herzegovina', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg' },
  { id: 30, alphacode: 'BW', Country: 'Botswana', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg' },
  { id: 31, alphacode: 'BV', Country: 'Bouvet Island', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BV.svg' },
  { id: 32, alphacode: 'BR', Country: 'Brazil', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg' },
  { id: 33, alphacode: 'IO', Country: 'British Indian Ocean Territory', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IO.svg' },
  { id: 34, alphacode: 'BN', Country: 'Brunei Darussalam', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg' },
  { id: 35, alphacode: 'BG', Country: 'Bulgaria', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg' },
  { id: 36, alphacode: 'BF', Country: 'Burkina Faso', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg' },
  { id: 37, alphacode: 'BI', Country: 'Burundi', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg' },
  { id: 38, alphacode: 'CV', Country: 'Cabo Verde', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg' },
  { id: 39, alphacode: 'KH', Country: 'Cambodia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg' },
  { id: 40, alphacode: 'CM', Country: 'Cameroon', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg' },
  { id: 41, alphacode: 'CA', Country: 'Canada', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg' },
  { id: 42, alphacode: 'KY', Country: 'Cayman Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KY.svg' },
  { id: 43, alphacode: 'CF', Country: 'Central African Republic', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg' },
  { id: 44, alphacode: 'TD', Country: 'Chad', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg' },
  { id: 45, alphacode: 'CL', Country: 'Chile', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg' },
  { id: 46, alphacode: 'CN', Country: 'China', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg' },
  { id: 47, alphacode: 'CX', Country: 'Christmas Island', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg' },
  { id: 48, alphacode: 'CC', Country: 'Cocos (Keeling) Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg' },
  { id: 49, alphacode: 'CO', Country: 'Colombia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg' },
  { id: 50, alphacode: 'KM', Country: 'Comoros', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg' },
  { id: 51, alphacode: 'CG', Country: 'Congo', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg' },
  { id: 52, alphacode: 'CD', Country: 'Congo (Democratic Republic of the)', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg' },
  { id: 53, alphacode: 'CK', Country: 'Cook Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg' },
  { id: 54, alphacode: 'CR', Country: 'Costa Rica', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg' },
  { id: 55, alphacode: 'CI', Country: 'Côte d\'Ivoire', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg' },
  { id: 56, alphacode: 'HR', Country: 'Croatia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg' },
  { id: 57, alphacode: 'CU', Country: 'Cuba', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg' },
  { id: 58, alphacode: 'CW', Country: 'Curaçao', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg' },
  { id: 59, alphacode: 'CY', Country: 'Cyprus', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg' },
  { id: 60, alphacode: 'CZ', Country: 'Czechia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg' },
  { id: 61, alphacode: 'DK', Country: 'Denmark', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg' },
  { id: 62, alphacode: 'DJ', Country: 'Djibouti', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg' },
  { id: 63, alphacode: 'DM', Country: 'Dominica', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg' },
  { id: 64, alphacode: 'DO', Country: 'Dominican Republic', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg' },
  { id: 65, alphacode: 'EC', Country: 'Ecuador', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg' },
  { id: 66, alphacode: 'EG', Country: 'Egypt', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg' },
  { id: 67, alphacode: 'SV', Country: 'El Salvador', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg' },
  { id: 68, alphacode: 'GQ', Country: 'Equatorial Guinea', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg' },
  { id: 69, alphacode: 'ER', Country: 'Eritrea', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg' },
  { id: 70, alphacode: 'EE', Country: 'Estonia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg' },
  { id: 71, alphacode: 'SZ', Country: 'Eswatini', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg' },
  { id: 72, alphacode: 'ET', Country: 'Ethiopia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg' },
  { id: 73, alphacode: 'FK', Country: 'Falkland Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg' },
  { id: 74, alphacode: 'FO', Country: 'Faroe Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg' },
  { id: 75, alphacode: 'FJ', Country: 'Fiji', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg' },
  { id: 76, alphacode: 'FI', Country: 'Finland', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg' },
  { id: 77, alphacode: 'FR', Country: 'France', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg' },
  { id: 78, alphacode: 'GF', Country: 'French Guiana', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg' },
  { id: 79, alphacode: 'PF', Country: 'French Polynesia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg' },
  { id: 80, alphacode: 'TF', Country: 'French Southern Territories', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TF.svg' },
  { id: 81, alphacode: 'GA', Country: 'Gabon', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg' },
  { id: 82, alphacode: 'GM', Country: 'Gambia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg' },
  { id: 83, alphacode: 'GE', Country: 'Georgia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg' },
  { id: 84, alphacode: 'DE', Country: 'Germany', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg' },
  { id: 85, alphacode: 'GH', Country: 'Ghana', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg' },
  { id: 86, alphacode: 'GI', Country: 'Gibraltar', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg' },
  { id: 87, alphacode: 'GR', Country: 'Greece', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg' },
  { id: 88, alphacode: 'GL', Country: 'Greenland', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg' },
  { id: 89, alphacode: 'GD', Country: 'Grenada', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg' },
  { id: 90, alphacode: 'GP', Country: 'Guadeloupe', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GP.svg' },
  { id: 91, alphacode: 'GU', Country: 'Guam', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg' },
  { id: 92, alphacode: 'GT', Country: 'Guatemala', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg' },
  { id: 93, alphacode: 'GG', Country: 'Guernsey', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GG.svg' },
  { id: 94, alphacode: 'GN', Country: 'Guinea', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg' },
  { id: 95, alphacode: 'GW', Country: 'Guinea-Bissau', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg' },
  { id: 96, alphacode: 'GY', Country: 'Guyana', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg' },
  { id: 97, alphacode: 'HT', Country: 'Haiti', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg' },
  { id: 98, alphacode: 'HM', Country: 'Heard Island and McDonald Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HM.svg' },
  { id: 99, alphacode: 'HN', Country: 'Honduras', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg' },
  { id: 100, alphacode: 'HK', Country: 'Hong Kong', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg' },
  { id: 101, alphacode: 'HU', Country: 'Hungary', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg' },
  { id: 102, alphacode: 'IS', Country: 'Iceland', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg' },
  { id: 103, alphacode: 'IN', Country: 'India', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg' },
  { id: 104, alphacode: 'ID', Country: 'Indonesia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg' },
  { id: 105, alphacode: 'IR', Country: 'Iran', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg' },
  { id: 106, alphacode: 'IQ', Country: 'Iraq', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg' },
  { id: 107, alphacode: 'IE', Country: 'Ireland', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg' },
  { id: 108, alphacode: 'IM', Country: 'Isle of Man', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg' },
  { id: 109, alphacode: 'IL', Country: 'Israel', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg' },
  { id: 110, alphacode: 'IT', Country: 'Italy', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg' },
  { id: 111, alphacode: 'JE', Country: 'Jersey', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg' },
  { id: 112, alphacode: 'JM', Country: 'Jamaica', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg' },
  { id: 113, alphacode: 'JP', Country: 'Japan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg' },
  { id: 114, alphacode: 'JE', Country: 'Jersey', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg' },
  { id: 115, alphacode: 'JO', Country: 'Jordan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg' },
  { id: 116, alphacode: 'KZ', Country: 'Kazakhstan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg' },
  { id: 117, alphacode: 'KE', Country: 'Kenya', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg' },
  { id: 118, alphacode: 'KI', Country: 'Kiribati', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg' },
  { id: 119, alphacode: 'KP', Country: 'Korea (North)', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg' },
  { id: 120, alphacode: 'KR', Country: 'Korea (South)', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg' },
  { id: 121, alphacode: 'KW', Country: 'Kuwait', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg' },
  { id: 122, alphacode: 'KG', Country: 'Kyrgyzstan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg' },
  { id: 123, alphacode: 'LA', Country: 'Laos', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg' },
  { id: 124, alphacode: 'LV', Country: 'Latvia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg' },
  { id: 125, alphacode: 'LB', Country: 'Lebanon', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg' },
  { id: 126, alphacode: 'LS', Country: 'Lesotho', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg' },
  { id: 127, alphacode: 'LR', Country: 'Liberia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg' },
  { id: 128, alphacode: 'LY', Country: 'Libya', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg' },
  { id: 129, alphacode: 'LI', Country: 'Liechtenstein', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg' },
  { id: 130, alphacode: 'LT', Country: 'Lithuania', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg' },
  { id: 131, alphacode: 'LU', Country: 'Luxembourg', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg' },
  { id: 132, alphacode: 'MO', Country: 'Macao', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg' },
  { id: 133, alphacode: 'MK', Country: 'North Macedonia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg' },
  { id: 134, alphacode: 'MG', Country: 'Madagascar', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg' },
  { id: 135, alphacode: 'MW', Country: 'Malawi', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg' },
  { id: 136, alphacode: 'MY', Country: 'Malaysia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg' },
  { id: 137, alphacode: 'MV', Country: 'Maldives', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg' },
  { id: 138, alphacode: 'ML', Country: 'Mali', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg' },
  { id: 139, alphacode: 'MT', Country: 'Malta', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg' },
  { id: 140, alphacode: 'MH', Country: 'Marshall Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg' },
  { id: 141, alphacode: 'MQ', Country: 'Martinique', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg' },
  { id: 142, alphacode: 'MR', Country: 'Mauritania', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg' },
  { id: 143, alphacode: 'MU', Country: 'Mauritius', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg' },
  { id: 144, alphacode: 'YT', Country: 'Mayotte', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg' },
  { id: 145, alphacode: 'MX', Country: 'Mexico', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg' },
  { id: 146, alphacode: 'FM', Country: 'Micronesia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg' },
  { id: 147, alphacode: 'MD', Country: 'Moldova', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg' },
  { id: 148, alphacode: 'MC', Country: 'Monaco', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg' },
  { id: 149, alphacode: 'MN', Country: 'Mongolia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg' },
  { id: 150, alphacode: 'ME', Country: 'Montenegro', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg' },
  { id: 151, alphacode: 'MS', Country: 'Montserrat', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg' },
  { id: 152, alphacode: 'MA', Country: 'Morocco', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg' },
  { id: 153, alphacode: 'MZ', Country: 'Mozambique', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg' },
  { id: 154, alphacode: 'MM', Country: 'Myanmar', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg' },
  { id: 155, alphacode: 'NA', Country: 'Namibia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg' },
  { id: 156, alphacode: 'NR', Country: 'Nauru', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg' },
  { id: 157, alphacode: 'NP', Country: 'Nepal', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg' },
  { id: 158, alphacode: 'NL', Country: 'Netherlands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg' },
  { id: 159, alphacode: 'NC', Country: 'New Caledonia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg' },
  { id: 160, alphacode: 'NZ', Country: 'New Zealand', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg' },
  { id: 161, alphacode: 'NI', Country: 'Nicaragua', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg' },
  { id: 162, alphacode: 'NE', Country: 'Niger', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg' },
  { id: 163, alphacode: 'NG', Country: 'Nigeria', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg' },
  { id: 164, alphacode: 'NU', Country: 'Niue', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg' },
  { id: 165, alphacode: 'NF', Country: 'Norfolk Island', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg' },
  { id: 166, alphacode: 'MP', Country: 'Northern Mariana Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg' },
  { id: 167, alphacode: 'NO', Country: 'Norway', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg' },
  { id: 168, alphacode: 'OM', Country: 'Oman', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg' },
  { id: 169, alphacode: 'PK', Country: 'Pakistan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg' },
  { id: 170, alphacode: 'PW', Country: 'Palau', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg' },
  { id: 171, alphacode: 'PS', Country: 'Palestine', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg' },
  { id: 172, alphacode: 'PA', Country: 'Panama', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg' },
  { id: 173, alphacode: 'PG', Country: 'Papua New Guinea', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg' },
  { id: 174, alphacode: 'PY', Country: 'Paraguay', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg' },
  { id: 175, alphacode: 'PE', Country: 'Peru', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg' },
  { id: 176, alphacode: 'PH', Country: 'Philippines', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg' },
  { id: 177, alphacode: 'PN', Country: 'Pitcairn Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg' },
  { id: 178, alphacode: 'PL', Country: 'Poland', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg' },
  { id: 179, alphacode: 'PT', Country: 'Portugal', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg' },
  { id: 180, alphacode: 'PR', Country: 'Puerto Rico', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg' },
  { id: 181, alphacode: 'QA', Country: 'Qatar', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg' },
  { id: 182, alphacode: 'RE', Country: 'Réunion', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg' },
  { id: 183, alphacode: 'RO', Country: 'Romania', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg' },
  { id: 184, alphacode: 'RU', Country: 'Russia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg' },
  { id: 185, alphacode: 'RW', Country: 'Rwanda', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg' },
  { id: 186, alphacode: 'SH', Country: 'Saint Helena', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg' },
  { id: 187, alphacode: 'KN', Country: 'Saint Kitts and Nevis', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg' },
  { id: 188, alphacode: 'LC', Country: 'Saint Lucia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg' },
  { id: 189, alphacode: 'PM', Country: 'Saint Pierre and Miquelon', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg' },
  { id: 190, alphacode: 'VC', Country: 'Saint Vincent and the Grenadines', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg' },
  { id: 191, alphacode: 'WS', Country: 'Samoa', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg' },
  { id: 192, alphacode: 'SM', Country: 'San Marino', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg' },
  { id: 193, alphacode: 'ST', Country: 'Sao Tome and Principe', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg' },
  { id: 194, alphacode: 'SA', Country: 'Saudi Arabia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg' },
  { id: 195, alphacode: 'SN', Country: 'Senegal', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg' },
  { id: 196, alphacode: 'RS', Country: 'Serbia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg' },
  { id: 197, alphacode: 'SC', Country: 'Seychelles', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg' },
  { id: 198, alphacode: 'SL', Country: 'Sierra Leone', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg' },
  { id: 199, alphacode: 'SG', Country: 'Singapore', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg' },
  { id: 200, alphacode: 'SX', Country: 'Sint Maarten', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg' },
  { id: 201, alphacode: 'SK', Country: 'Slovakia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg' },
  { id: 202, alphacode: 'SI', Country: 'Slovenia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg' },
  { id: 203, alphacode: 'SB', Country: 'Solomon Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg' },
  { id: 204, alphacode: 'SO', Country: 'Somalia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg' },
  { id: 205, alphacode: 'ZA', Country: 'South Africa', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg' },
  { id: 206, alphacode: 'GS', Country: 'South Georgia and the South Sandwich Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GS.svg' },
  { id: 207, alphacode: 'SS', Country: 'South Sudan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg' },
  { id: 208, alphacode: 'ES', Country: 'Spain', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg' },
  { id: 209, alphacode: 'LK', Country: 'Sri Lanka', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg' },
  { id: 210, alphacode: 'SD', Country: 'Sudan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg' },
  { id: 211, alphacode: 'SR', Country: 'Suriname', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg' },
  { id: 212, alphacode: 'SJ', Country: 'Svalbard and Jan Mayen', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg' },
  { id: 213, alphacode: 'SE', Country: 'Sweden', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg' },
  { id: 214, alphacode: 'CH', Country: 'Switzerland', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg' },
  { id: 215, alphacode: 'SY', Country: 'Syria', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg' },
  { id: 216, alphacode: 'TW', Country: 'Taiwan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg' },
  { id: 217, alphacode: 'TJ', Country: 'Tajikistan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg' },
  { id: 218, alphacode: 'TZ', Country: 'Tanzania', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg' },
  { id: 219, alphacode: 'TH', Country: 'Thailand', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg' },
  { id: 220, alphacode: 'TL', Country: 'Timor-Leste', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg' },
  { id: 221, alphacode: 'TG', Country: 'Togo', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg' },
  { id: 222, alphacode: 'TK', Country: 'Tokelau', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TK.svg' },
  { id: 223, alphacode: 'TO', Country: 'Tonga', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg' },
  { id: 224, alphacode: 'TT', Country: 'Trinidad and Tobago', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg' },
  { id: 225, alphacode: 'TN', Country: 'Tunisia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg' },
  { id: 226, alphacode: 'TR', Country: 'Turkey', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg' },
  { id: 227, alphacode: 'TM', Country: 'Turkmenistan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg' },
  { id: 228, alphacode: 'TC', Country: 'Turks and Caicos Islands', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg' },
  { id: 229, alphacode: 'TV', Country: 'Tuvalu', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg' },
  { id: 230, alphacode: 'UG', Country: 'Uganda', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg' },
  { id: 231, alphacode: 'UA', Country: 'Ukraine', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg' },
  { id: 232, alphacode: 'AE', Country: 'United Arab Emirates', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg' },
  { id: 233, alphacode: 'GB', Country: 'United Kingdom', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg' },
  { id: 234, alphacode: 'US', Country: 'United States', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg' },
  { id: 235, alphacode: 'UY', Country: 'Uruguay', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg' },
  { id: 236, alphacode: 'UZ', Country: 'Uzbekistan', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg' },
  { id: 237, alphacode: 'VU', Country: 'Vanuatu', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg' },
  { id: 238, alphacode: 'VE', Country: 'Venezuela', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg' },
  { id: 239, alphacode: 'VN', Country: 'Vietnam', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg' },
  { id: 240, alphacode: 'WF', Country: 'Wallis and Futuna', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg' },
  { id: 241, alphacode: 'EH', Country: 'Western Sahara', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EH.svg' },
  { id: 242, alphacode: 'YE', Country: 'Yemen', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg' },
  { id: 243, alphacode: 'ZM', Country: 'Zambia', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg' },
  { id: 244, alphacode: 'ZW', Country: 'Zimbabwe', flagUrl: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg' },
];

export const TosList = [
    {
      id: 1,
      title: 'Acceptance and Modification of Terms',
      content: `a. Acceptance of Terms
  Our websites and apps are provided to you subject to these Terms. These Terms constitute a binding agreement between you and RemoteConnect. By accessing or using our websites and apps, you agree to accept and be bound by these Terms.
  
  b. Changes to Terms
  We may update these Terms periodically to reflect changes in our services or legal requirements. The updated version will apply to you, and the current Terms will be accessible through our websites and apps.
  
  c. Notification of Modifications
  If we believe that the updates to these Terms will have a significant impact on you, we will notify you through our websites and/or apps at least 30 days before the changes are implemented.
  
  d. Continuation of Use
  If you disagree with any version of the Terms, please stop using our websites and apps. By continuing to use them after changes are implemented, you agree to the revised Terms.
  
  e. Conflicting Agreements
  Your use of our services (including our websites and apps) may be subject to additional agreements with RemoteConnect. If there is a conflict between these Terms and any other agreements, the terms of the additional agreements will take precedence.`
    }
    // Add more TOS items as needed
  ];