export const Countrylist = [
    { id: 1, alphacode: 'AF', Country: 'Afghanistan' },
    { id: 2, alphacode: 'AX', Country: 'Åland Islands' },
    { id: 3, alphacode: 'AL', Country: 'Albania' },
    { id: 4, alphacode: 'DZ', Country: 'Algeria' },
    { id: 5, alphacode: 'AS', Country: 'American Samoa' },
    { id: 6, alphacode: 'AD', Country: 'Andorra' },
    { id: 7, alphacode: 'AO', Country: 'Angola' },
    { id: 8, alphacode: 'AI', Country: 'Anguilla' },
    { id: 9, alphacode: 'AQ', Country: 'Antarctica' },
    { id: 10, alphacode: 'AG', Country: 'Antigua and Barbuda' },
    { id: 11, alphacode: 'AR', Country: 'Argentina' },
    { id: 12, alphacode: 'AM', Country: 'Armenia' },
    { id: 13, alphacode: 'AW', Country: 'Aruba' },
    { id: 14, alphacode: 'AU', Country: 'Australia' },
    { id: 15, alphacode: 'AT', Country: 'Austria' },
    { id: 16, alphacode: 'AZ', Country: 'Azerbaijan' },
    { id: 17, alphacode: 'BS', Country: 'Bahamas' },
    { id: 18, alphacode: 'BH', Country: 'Bahrain' },
    { id: 19, alphacode: 'BD', Country: 'Bangladesh' },
    { id: 20, alphacode: 'BB', Country: 'Barbados' },
    { id: 21, alphacode: 'BY', Country: 'Belarus' },
    { id: 22, alphacode: 'BE', Country: 'Belgium' },
    { id: 23, alphacode: 'BZ', Country: 'Belize' },
    { id: 24, alphacode: 'BJ', Country: 'Benin' },
    { id: 25, alphacode: 'BM', Country: 'Bermuda' },
    { id: 26, alphacode: 'BT', Country: 'Bhutan' },
    { id: 27, alphacode: 'BO', Country: 'Bolivia (Plurinational State of)' },
    { id: 28, alphacode: 'BQ', Country: 'Bonaire, Sint Eustatius and Saba' },
    { id: 29, alphacode: 'BA', Country: 'Bosnia and Herzegovina' },
    { id: 30, alphacode: 'BW', Country: 'Botswana' },
    { id: 31, alphacode: 'BV', Country: 'Bouvet Island' },
    { id: 32, alphacode: 'BR', Country: 'Brazil' },
    { id: 33, alphacode: 'IO', Country: 'British Indian Ocean Territory' },
    { id: 34, alphacode: 'BN', Country: 'Brunei Darussalam' },
    { id: 35, alphacode: 'BG', Country: 'Bulgaria' },
    { id: 36, alphacode: 'BF', Country: 'Burkina Faso' },
    { id: 37, alphacode: 'BI', Country: 'Burundi' },
    { id: 38, alphacode: 'CV', Country: 'Cabo Verde' },
    { id: 39, alphacode: 'KH', Country: 'Cambodia' },
    { id: 40, alphacode: 'CM', Country: 'Cameroon' },
    { id: 41, alphacode: 'CA', Country: 'Canada' },
    { id: 42, alphacode: 'KY', Country: 'Cayman Islands' },
    { id: 43, alphacode: 'CF', Country: 'Central African Republic' },
    { id: 44, alphacode: 'TD', Country: 'Chad' },
    { id: 45, alphacode: 'CL', Country: 'Chile' },
    { id: 46, alphacode: 'CN', Country: 'China' },
    { id: 47, alphacode: 'CX', Country: 'Christmas Island' },
    { id: 48, alphacode: 'CC', Country: 'Cocos (Keeling) Islands' },
    { id: 49, alphacode: 'CO', Country: 'Colombia' },
    { id: 50, alphacode: 'KM', Country: 'Comoros' },
    { id: 51, alphacode: 'CG', Country: 'Congo' },
    { id: 52, alphacode: 'CD', Country: 'Congo (Democratic Republic of the)' },
    { id: 53, alphacode: 'CK', Country: 'Cook Islands' },
    { id: 54, alphacode: 'CR', Country: 'Costa Rica' },
    { id: 55, alphacode: 'HR', Country: 'Croatia' },
    { id: 56, alphacode: 'CU', Country: 'Cuba' },
    { id: 57, alphacode: 'CW', Country: 'Curaçao' },
    { id: 58, alphacode: 'CY', Country: 'Cyprus' },
    { id: 59, alphacode: 'CZ', Country: 'Czech Republic' },
    { id: 60, alphacode: 'DK', Country: 'Denmark' },
    { id: 61, alphacode: 'DJ', Country: 'Djibouti' },
    { id: 62, alphacode: 'DM', Country: 'Dominica' },
    { id: 63, alphacode: 'DO', Country: 'Dominican Republic' },
    { id: 64, alphacode: 'EC', Country: 'Ecuador' },
    { id: 65, alphacode: 'EG', Country: 'Egypt' },
    { id: 66, alphacode: 'SV', Country: 'El Salvador' },
    { id: 67, alphacode: 'GQ', Country: 'Equatorial Guinea' },
    { id: 68, alphacode: 'ER', Country: 'Eritrea' },
    { id: 69, alphacode: 'EE', Country: 'Estonia' },
    { id: 70, alphacode: 'ET', Country: 'Ethiopia' },
    { id: 71, alphacode: 'FK', Country: 'Falkland Islands (Malvinas)' },
    { id: 72, alphacode: 'FO', Country: 'Faroe Islands' },
    { id: 73, alphacode: 'FJ', Country: 'Fiji' },
    { id: 74, alphacode: 'FI', Country: 'Finland' },
    { id: 75, alphacode: 'FR', Country: 'France' },
    { id: 76, alphacode: 'GF', Country: 'French Guiana' },
    { id: 77, alphacode: 'PF', Country: 'French Polynesia' },
    { id: 78, alphacode: 'TF', Country: 'French Southern Territories' },
    { id: 79, alphacode: 'GA', Country: 'Gabon' },
    { id: 80, alphacode: 'GM', Country: 'Gambia' },
    { id: 81, alphacode: 'GE', Country: 'Georgia' },
    { id: 82, alphacode: 'DE', Country: 'Germany' },
    { id: 83, alphacode: 'GH', Country: 'Ghana' },
    { id: 84, alphacode: 'GI', Country: 'Gibraltar' },
    { id: 85, alphacode: 'GR', Country: 'Greece' },
    { id: 86, alphacode: 'GL', Country: 'Greenland' },
    { id: 87, alphacode: 'GD', Country: 'Grenada' },
    { id: 88, alphacode: 'GP', Country: 'Guadeloupe' },
    { id: 89, alphacode: 'GU', Country: 'Guam' },
    { id: 90, alphacode: 'GT', Country: 'Guatemala' },
    { id: 91, alphacode: 'GG', Country: 'Guernsey' },
    { id: 92, alphacode: 'GN', Country: 'Guinea' },
    { id: 93, alphacode: 'GW', Country: 'Guinea-Bissau' },
    { id: 94, alphacode: 'GY', Country: 'Guyana' },
    { id: 95, alphacode: 'HT', Country: 'Haiti' },
    { id: 96, alphacode: 'HM', Country: 'Heard Island and McDonald Islands' },
    { id: 97, alphacode: 'VA', Country: 'Holy See' },
    { id: 98, alphacode: 'HN', Country: 'Honduras' },
    { id: 99, alphacode: 'HK', Country: 'Hong Kong' },
    { id: 100, alphacode: 'HU', Country: 'Hungary' },
    { id: 101, alphacode: 'IS', Country: 'Iceland' },
    { id: 102, alphacode: 'IN', Country: 'India' },
    { id: 103, alphacode: 'ID', Country: 'Indonesia' },
    { id: 104, alphacode: 'IR', Country: 'Iran (Islamic Republic of)' },
    { id: 105, alphacode: 'IQ', Country: 'Iraq' },
    { id: 106, alphacode: 'IE', Country: 'Ireland' },
    { id: 107, alphacode: 'IM', Country: 'Isle of Man' },
    { id: 109, alphacode: 'IT', Country: 'Italy' },
    { id: 110, alphacode: 'JM', Country: 'Jamaica' },
    { id: 111, alphacode: 'JP', Country: 'Japan' },
    { id: 112, alphacode: 'JE', Country: 'Jersey' },
    { id: 113, alphacode: 'JO', Country: 'Jordan' },
    { id: 114, alphacode: 'KZ', Country: 'Kazakhstan' },
    { id: 115, alphacode: 'KE', Country: 'Kenya' },
    { id: 116, alphacode: 'KI', Country: 'Kiribati' },
    { id: 117, alphacode: 'KP', Country: "Korea (Democratic Peoples Republic of)"},
    { id: 118, alphacode: 'KR', Country: "Korea (Republic of)" },
    { id: 119, alphacode: 'KW', Country: 'Kuwait' },
    { id: 120, alphacode: 'KG', Country: 'Kyrgyzstan' },
    { id: 121, alphacode: 'LA', Country: "Lao People's Democratic Republic" },
    { id: 122, alphacode: 'LV', Country: 'Latvia' },
    { id: 123, alphacode: 'LB', Country: 'Lebanon' },
    { id: 124, alphacode: 'LS', Country: 'Lesotho' },
    { id: 125, alphacode: 'LR', Country: 'Liberia' },
    { id: 126, alphacode: 'LY', Country: 'Libya' },
    { id: 127, alphacode: 'LI', Country: 'Liechtenstein' },
    { id: 128, alphacode: 'LT', Country: 'Lithuania' },
    { id: 129, alphacode: 'LU', Country: 'Luxembourg' },
    { id: 130, alphacode: 'MO', Country: 'Macao' },
    { id: 131, alphacode: 'MK', Country: 'Macedonia (the former Yugoslav Republic of)' },
    { id: 132, alphacode: 'MG', Country: 'Madagascar' },
    { id: 133, alphacode: 'MW', Country: 'Malawi' },
    { id: 134, alphacode: 'MY', Country: 'Malaysia' },
    { id: 135, alphacode: 'MV', Country: 'Maldives' },
    { id: 136, alphacode: 'ML', Country: 'Mali' },
    { id: 137, alphacode: 'MT', Country: 'Malta' },
    { id: 138, alphacode: 'MH', Country: 'Marshall Islands' },
    { id: 139, alphacode: 'MQ', Country: 'Martinique' },
    { id: 140, alphacode: 'MR', Country: 'Mauritania' },
    { id: 141, alphacode: 'MU', Country: 'Mauritius' },
    { id: 142, alphacode: 'YT', Country: 'Mayotte' },
    { id: 143, alphacode: 'MX', Country: 'Mexico' },
    { id: 144, alphacode: 'FM', Country: 'Micronesia (Federated States of)' },
    { id: 145, alphacode: 'MD', Country: 'Moldova (Republic of)' },
    { id: 146, alphacode: 'MC', Country: 'Monaco' },
    { id: 147, alphacode: 'MN', Country: 'Mongolia' },
    { id: 148, alphacode: 'ME', Country: 'Montenegro' },
    { id: 149, alphacode: 'MS', Country: 'Montserrat' },
    { id: 150, alphacode: 'MA', Country: 'Morocco' },
    { id: 151, alphacode: 'MZ', Country: 'Mozambique' },
    { id: 152, alphacode: 'MM', Country: 'Myanmar' },
    { id: 153, alphacode: 'NA', Country: 'Namibia' },
    { id: 154, alphacode: 'NR', Country: 'Nauru' },
    { id: 155, alphacode: 'NP', Country: 'Nepal' },
    { id: 156, alphacode: 'NL', Country: 'Netherlands' },
    { id: 157, alphacode: 'NC', Country: 'New Caledonia' },
    { id: 158, alphacode: 'NZ', Country: 'New Zealand' },
    { id: 159, alphacode: 'NI', Country: 'Nicaragua' },
    { id: 160, alphacode: 'NE', Country: 'Niger' },
    { id: 161, alphacode: 'NG', Country: 'Nigeria' },
    { id: 162, alphacode: 'NU', Country: 'Niue' },
    { id: 163, alphacode: 'NF', Country: 'Norfolk Island' },
    { id: 164, alphacode: 'MP', Country: 'Northern Mariana Islands' },
    { id: 165, alphacode: 'NO', Country: 'Norway' },
    { id: 166, alphacode: 'OM', Country: 'Oman' },
    { id: 167, alphacode: 'PK', Country: 'Pakistan' },
    { id: 168, alphacode: 'PW', Country: 'Palau' },
    { id: 169, alphacode: 'PS', Country: 'Palestine, State of' },
    { id: 170, alphacode: 'PA', Country: 'Panama' },
    { id: 171, alphacode: 'PG', Country: 'Papua New Guinea' },
    { id: 172, alphacode: 'PY', Country: 'Paraguay' },
    { id: 173, alphacode: 'PE', Country: 'Peru' },
    { id: 174, alphacode: 'PH', Country: 'Philippines' },
    { id: 175, alphacode: 'PN', Country: 'Pitcairn' },
    { id: 176, alphacode: 'PL', Country: 'Poland' },
    { id: 177, alphacode: 'PT', Country: 'Portugal' },
    { id: 178, alphacode: 'PR', Country: 'Puerto Rico' },
    { id: 179, alphacode: 'QA', Country: 'Qatar' },
    { id: 180, alphacode: 'RE', Country: 'Réunion' },
    { id: 181, alphacode: 'RO', Country: 'Romania' },
    { id: 182, alphacode: 'RU', Country: 'Russian Federation' },
    { id: 183, alphacode: 'RW', Country: 'Rwanda' },
    { id: 184, alphacode: 'BL', Country: 'Saint Barthélemy' },
    { id: 185, alphacode: 'SH', Country: 'Saint Helena, Ascension and Tristan da Cunha' },
    { id: 186, alphacode: 'KN', Country: 'Saint Kitts and Nevis' },
    { id: 187, alphacode: 'LC', Country: 'Saint Lucia' },
    { id: 188, alphacode: 'MF', Country: 'Saint Martin (French part)' },
    { id: 189, alphacode: 'PM', Country: 'Saint Pierre and Miquelon' },
    { id: 190, alphacode: 'VC', Country: 'Saint Vincent and the Grenadines' },
    { id: 191, alphacode: 'WS', Country: 'Samoa' },
    { id: 192, alphacode: 'SM', Country: 'San Marino' },
    { id: 193, alphacode: 'ST', Country: 'Sao Tome and Principe' },
    { id: 194, alphacode: 'SA', Country: 'Saudi Arabia' },
    { id: 195, alphacode: 'SN', Country: 'Senegal' },
    { id: 196, alphacode: 'RS', Country: 'Serbia' },
    { id: 197, alphacode: 'SC', Country: 'Seychelles' },
    { id: 198, alphacode: 'SL', Country: 'Sierra Leone' },
    { id: 199, alphacode: 'SG', Country: 'Singapore' },
    { id: 200, alphacode: 'SX', Country: 'Sint Maarten (Dutch part)' },
    { id: 201, alphacode: 'SK', Country: 'Slovakia' },
    { id: 202, alphacode: 'SI', Country: 'Slovenia' },
    { id: 203, alphacode: 'SB', Country: 'Solomon Islands' },
    { id: 204, alphacode: 'SO', Country: 'Somalia' },
    { id: 205, alphacode: 'ZA', Country: 'South Africa' },
    { id: 206, alphacode: 'GS', Country: 'South Georgia and the South Sandwich Islands' },
    { id: 207, alphacode: 'SS', Country: 'South Sudan' },
    { id: 208, alphacode: 'ES', Country: 'Spain' },
    { id: 209, alphacode: 'LK', Country: 'Sri Lanka' },
    { id: 210, alphacode: 'SD', Country: 'Sudan' },
    { id: 211, alphacode: 'SR', Country: 'Suriname' },
    { id: 212, alphacode: 'SJ', Country: 'Svalbard and Jan Mayen' },
    { id: 213, alphacode: 'SZ', Country: 'Swaziland' },
    { id: 214, alphacode: 'SE', Country: 'Sweden' },
    { id: 215, alphacode: 'CH', Country: 'Switzerland' },
    { id: 216, alphacode: 'SY', Country: 'Syrian Arab Republic' },
    { id: 217, alphacode: 'TW', Country: 'Taiwan, Province of China' },
    { id: 218, alphacode: 'TJ', Country: 'Tajikistan' },
    { id: 219, alphacode: 'TZ', Country: 'Tanzania, United Republic of' },
    { id: 220, alphacode: 'TH', Country: 'Thailand' },
    { id: 221, alphacode: 'TL', Country: 'Timor-Leste' },
    { id: 222, alphacode: 'TG', Country: 'Togo' },
    { id: 223, alphacode: 'TK', Country: 'Tokelau' },
    { id: 224, alphacode: 'TO', Country: 'Tonga' },
    { id: 225, alphacode: 'TT', Country: 'Trinidad and Tobago' },
    { id: 226, alphacode: 'TN', Country: 'Tunisia' },
    { id: 227, alphacode: 'TR', Country: 'Turkey' },
    { id: 228, alphacode: 'TM', Country: 'Turkmenistan' },
    { id: 229, alphacode: 'TC', Country: 'Turks and Caicos Islands' },
    { id: 230, alphacode: 'TV', Country:'Tuvalu' },
    { id: 231, alphacode: 'UG', Country: 'Uganda' },
    { id: 232, alphacode: 'UA', Country: 'Ukraine' },
    { id: 233, alphacode: 'AE', Country: 'United Arab Emirates' },
    { id: 234, alphacode: 'GB', Country: 'United Kingdom of Great Britain and Northern Ireland' },
    { id: 235, alphacode: 'UM', Country: 'United States Minor Outlying Islands' },
    { id: 236, alphacode: 'US', Country: 'United States of America' },
    { id: 237, alphacode: 'UY', Country: 'Uruguay' },
    { id: 238, alphacode: 'UZ', Country: 'Uzbekistan' },
    { id: 239, alphacode: 'VU', Country: 'Vanuatu' },
    { id: 240, alphacode: 'VE', Country: 'Venezuela (Bolivarian Republic of)' },
    { id: 241, alphacode: 'VN', Country: 'Viet Nam' },
    { id: 242, alphacode: 'VG', Country: 'Virgin Islands (British)' },
    { id: 243, alphacode: 'VI', Country: 'Virgin Islands (U.S.)' },
    { id: 244, alphacode: 'WF', Country: 'Wallis and Futuna' },
    { id: 245, alphacode: 'EH', Country: 'Western Sahara' },
    { id: 246, alphacode: 'YE', Country: 'Yemen' },
    { id: 247, alphacode: 'ZM', Country: 'Zambia' },
    { id: 248, alphacode: 'ZW', Country: 'Zimbabwe' }
];

export const TosList = [
    {
      id: 1,
      title: 'Acceptance and Modification of Terms',
      content: `a. Acceptance of Terms
  Our websites and apps are provided to you subject to these Terms. These Terms constitute a binding agreement between you and RemoteConnect. By accessing or using our websites and apps, you agree to accept and be bound by these Terms.
  
  b. Changes to Terms
  We may update these Terms periodically to reflect changes in our services or legal requirements. The updated version will apply to you, and the current Terms will be accessible through our websites and apps.
  
  c. Notification of Modifications
  If we believe that the updates to these Terms will have a significant impact on you, we will notify you through our websites and/or apps at least 30 days before the changes are implemented.
  
  d. Continuation of Use
  If you disagree with any version of the Terms, please stop using our websites and apps. By continuing to use them after changes are implemented, you agree to the revised Terms.
  
  e. Conflicting Agreements
  Your use of our services (including our websites and apps) may be subject to additional agreements with RemoteConnect. If there is a conflict between these Terms and any other agreements, the terms of the additional agreements will take precedence.`
    }
    // Add more TOS items as needed
  ];